/servo_pan/servo_pan:
  ros__parameters:
    servo_id: 0
    dir: 1
    gain_P: 1.0

/**:
  ros__parameters:
    operation_mode: "control"
    driver_device: "arduino"
    control_frequency: 0.05
    pwm_min: 2400
    pwm_max: 9600
    angle_min: 0
    angle_software_min: 0
    angle_max: 180
    angle_software_max: 180
    speed_max: 200.0