/servo_driver_waveshare:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baudrate: 115200

/**:
  ros__parameters:
    operation_mode: "control"
    driver_device: "waveshare"
    pwm_min: 0
    pwm_max: 4095
    angle_min: 0
    angle_software_min: 0
    angle_max: 360
    angle_software_max: 360
    speed_max: 500
    gain_P: 0.2
    gain_D: 0.5

/head/yaw/servo:
  ros__parameters:
    servo_id: 8
    angle_software_min: 120
    angle_software_max: 230
    dir: -1

/head/pitch/servo:
  ros__parameters:
    servo_id: 9
    angle_software_min: 120
    angle_software_max: 230
    dir: 1
